"""
System #13: Reports Generator
System #14: Backup System  
System #15: Multi-language Support
"""

from flask import Blueprint, jsonify, request, render_template_string, send_file
from datetime import datetime
import io
import random

bp = Blueprint('reports', __name__)

# ═══════ Reports Storage ═════

reports_history = [
    {"id": 1, "name": "Security Audit Report", "type": "security", "date": "2024-01-15", "size": "2.4 MB", "status": "ready", "format": "PDF"},
    {"id": 2, "name": "VPN Usage Statistics", "type": "analytics", "date": "2024-01-14", "size": "1.1 MB", "status": "ready", "format": "Excel"},
    {"id": 3, "name": "User Activity Log", "type": "activity", "date": "2024-01-14", "size": "856 KB", "status": "ready", "format": "CSV"},
]

backups = [
    {"id": 1, "date": "2024-01-15 02:00 AM", "size": "45 MB", "type": "full", "status": "completed"},
    {"id": 2, "date": "2024-01-14 02:00 AM", "size": "44 MB", "type": "full", "status": "completed"},
    {"id": 3, "date": "2024-01-13 02:00 AM", "size": "43 MB", "type": "incremental", "status": "completed"},
]

translations = {
    "ar": {
        "dashboard": "لوحة التحكم",
        "analytics": "التحليلات",
        "users": "المستخدمين",
        "reports": "التقارير",
        "settings": "الإعدادات",
        "login": "تسجيل الدخول",
        "logout": "تسجيل الخروج",
        "save": "حفظ",
        "cancel": "إلغاء",
        "search": "بحث...",
        "loading": "جاري التحميل...",
        "home": "الرئيسية",
        "vpn_manager": "مدير VPN",
        "activity_log": "سجل الأنشطة",
        "notifications": "الإشعارات",
        "backup": "نسخ احتياطي",
        "language": "اللغة"
    },
    "en": {
        "dashboard": "Dashboard",
        "analytics": "Analytics",
        "users": "Users",
        "reports": "Reports",
        "settings": "Settings",
        "login": "Login",
        "logout": "Logout",
        "save": "Save",
        "cancel": "Cancel",
        "search": "Search...",
        "loading": "Loading...",
        "home": "Home",
        "vpn_manager": "VPN Manager",
        "activity_log": "Activity Log",
        "notifications": "Notifications",
        "backup": "Backup",
        "language": "Language"
    }
}

current_lang = "ar"

# ═══════ Routes ═════

@bp.route('/')
def reports_dashboard():
    return render_template_string(REPORTS_DASHBOARD)

@bp.route('/api/reports')
def api_reports():
    return jsonify({"success": True, "reports": reports_history})

@bp.route('/api/reports/generate', methods=['POST'])
def api_generate_report():
    data = request.json or {}
    report_type = data.get("type", "general")
    format_type = data.get("format", "pdf")
    
    new_report = {
        "id": len(reports_history) + 1,
        "name": f"{report_type.capitalize()} Report - {datetime.now().strftime('%Y-%m-%d')}",
        "type": report_type,
        "date": datetime.now().strftime('%Y-%m-%d'),
        "size": f"{random.randint(500, 3000)} KB",
        "status": "generating",
        "format": format_type.upper()
    }
    reports_history.insert(0, new_report)
    
    return jsonify({"success": True, "report": new_report, "message": "Report generation started"})

@bp.route('/api/reports/<int:report_id>/download')
def api_download_report(report_id):
    report = next((r for r in reports_history if r["id"] == report_id), None)
    if not report:
        return jsonify({"success": False, "error": "Not found"}), 404
    
    content = f"""Security Toolkit PRO v4.0 - Report
====================================
Report ID: {report['id']}
Name: {report['name']}
Type: {report['type']}
Generated: {report['date']}

--- Summary ---
Total Visits: {random.randint(500,2000)}
Active Users: {random.randint(10,100)}
Security Incidents: {random.randint(0,5)}
VPN Connections: {random.randint(5,50)}

--- Generated by Security Toolkit PRO ---
https://security-toolkit-pro.onrender.com
"""
    
    output = io.BytesIO(content.encode())
    return send_file(output, as_attachment=True, download_name=f"report_{report_id}.txt")

@bp.route('/api/backups')
def api_backups():
    return jsonify({"success": True, "backups": backups})

@bp.route('/api/backups/create', methods=['POST'])
def api_create_backup():
    new_backup = {
        "id": len(backups) + 1,
        "date": datetime.now().strftime('%Y-%m-%d %I:%M %p'),
        "size": f"{len(backups) + 42} MB",
        "type": "full",
        "status": "in_progress"
    }
    backups.insert(0, new_backup)
    return jsonify({"success": True, "backup": new_backup})

@bp.route('/api/language')
def api_language():
    return jsonify({"success": True, "current": current_lang, "available": list(translations.keys())})

@bp.route('/api/language/<lang>')
def api_set_language(lang):
    global current_lang
    if lang in translations:
        current_lang = lang
        return jsonify({"success": True, "language": lang, "strings": translations[lang]})
    return jsonify({"success": False, "error": "Language not supported"})

@bp.route('/api/translate')
def api_translate():
    return jsonify({"success": True, "strings": translations[current_lang]})

# ═════ HTML Template ═════

REPORTS_DASHBOARD = '''<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <title>📈 Reports & Backup | Security Toolkit</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css" rel="stylesheet">
    <style>
        :root{--primary:#6f42c1;--dark:#0f0f23;--card:#1a1a3e}
        *{box-sizing:border-box}
        body{background:var(--dark);color:#eee;font-family:'Segoe UI',sans-serif;margin:0;padding:20px}
        .main-card{background:var(--card);border-radius:15px;border:1px solid rgba(111,66,193,.3);padding:20px;margin-bottom:20px}
        .report-item{background:rgba(255,255,255,.03);border-radius:10px;padding:15px;margin-bottom:10px;display:flex;justify-content:space-between;align-items:center}
        .backup-item{background:rgba(255,255,255,.03);border-radius:10px;padding:12px;margin-bottom:8px;border-right:3px solid #198754}
        .format-pdf{color:#dc3545}.format-excel{color:#198754}.format-csv{color:#6f42c1}
        .lang-btn{padding:8px 20px;border-radius:20px;border:1px solid rgba(255,255,255,.2);background:transparent;color:#fff;cursor:pointer;transition:all .3s}
        .lang-btn:hover,.lang-btn.active{background:var(--primary);border-color:var(--primary)}
        .stat-mini{background:rgba(111,66,193,.1);border-radius:10px;padding:15px;text-align:center}
    </style>
</head>
<body>
<div class="container-fluid">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h3><i class="bi bi-file-earmark-bar-graph me-2"></i>Reports & Backups</h3>
        <div class="d-flex gap-2">
            <button class="lang-btn active" onclick="setLang('ar')">🇸🇦 عربي</button>
            <button class="lang-btn" onclick="setLang('en')">🇺🇸 English</button>
        </div>
    </div>

    <!-- Quick Stats -->
    <div class="row g-3 mb-4">
        <div class="col-md-3"><div class="stat-mini"><i class="bi bi-file-earmark-text fs-3 text-primary d-block"></i><h4 id="reports-count">0</h4><small>Reports</small></div></div>
        <div class="col-md-3"><div class="stat-mini"><i class="bi bi-hdd-stack fs-3 text-success d-block"></i><h4 id="backups-count">0</h4><small>Backups</small></div></div>
        <div class="col-md-3"><div class="stat-mini"><i class="bi bi-download fs-3 text-info d-block"></i><h4 id="total-size">0 MB</h4><small>Total Size</small></div></div>
        <div class="col-md-3"><div class="stat-mini"><i class="bi bi-translate fs-3 text-warning d-block"></i><h4 id="curr-lang">AR</h4><small>Language</small></div></div>
    </div>

    <div class="row g-4">
        <div class="col-lg-6">
            <!-- Reports -->
            <div class="main-card">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h6 class="mb-0"><i class="bi bi-file-earmark-text me-2"></i>Reports</h6>
                    <button class="btn btn-primary btn-sm" onclick="generateReport()">
                        <i class="bi bi-plus-lg me-1"></i>New Report
                    </button>
                </div>
                <div id="reports-list"></div>
            </div>
        </div>
        
        <div class="col-lg-6">
            <!-- Backups -->
            <div class="main-card">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h6 class="mb-0"><i class="bi bi-hdd-stack me-2"></i>Backups</h6>
                    <button class="btn btn-success btn-sm" onclick="createBackup()">
                        <i class="bi bi-download me-1"></i>Create Backup
                    </button>
                </div>
                <div id="backups-list"></div>
            </div>
            
            <!-- Translations -->
            <div class="main-card mt-4">
                <h6 class="mb-3"><i class="bi bi-translate me-2"></i>Translations / الترجمة</h6>
                <div id="translated-strings" class="small"></div>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script>
document.addEventListener('DOMContentLoaded', function() {
    loadReports();
    loadBackups();
});

async function loadReports() {
    const r = await fetch('/reports/api/reports');
    const d = await r.json();
    document.getElementById('reports-count').textContent = d.reports.length;
    
    let totalSize = 0;
    document.getElementById('reports-list').innerHTML = d.reports.map(rep => {
        totalSize += parseFloat(rep.size);
        return `<div class="report-item">
            <div>
                <strong><i class="bi bi-file-earmark me-2 format-${rep.format.toLowerCase()}"></i>${rep.name}</strong><br>
                <small class="text-muted">${rep.date} • ${rep.size} • ${rep.format}</small>
            </div>
            <div>
                <span class="badge ${rep.status==='ready'?'bg-success':'bg-warning'}">${rep.status}</span>
                <button class="btn btn-sm btn-outline-primary ms-2" onclick="window.location.href='/reports/api/reports/${rep.id}/download'">
                    <i class="bi bi-download"></i>
                </button>
            </div>
        </div>`;
    }).join('');
    
    document.getElementById('total-size').textContent = Math.round(totalSize) + ' MB';
}

async function generateReport() {
    await fetch('/reports/api/reports/generate', {
        method:'POST',
        headers:{'Content-Type':'application/json'},
        body:JSON.stringify({type:'security', format:'pdf'})
    });
    loadReports();
}

async function loadBackups() {
    const r = await fetch('/reports/api/backups');
    const d = await r.json();
    document.getElementById('backups-count').textContent = d.backups.length;
    document.getElementById('backups-list').innerHTML = d.backups.map(b => `
        <div class="backup-item">
            <div class="d-flex justify-content-between">
                <div>
                    <strong>Backup #${b.id}</strong>
                    <small class="text-muted d-block">${b.date} • ${b.size} • ${b.type}</small>
                </div>
                <span class="badge ${b.status==='completed'?'bg-success':'bg-warning'}">${b.status}</span>
            </div>
        </div>`).join('');
}

async function createBackup() {
    await fetch('/reports/api/backups/create', {method:'POST'});
    loadBackups();
}

async function setLang(lang) {
    document.querySelectorAll('.lang-btn').forEach(b=>b.classList.remove('active'));
    event.target.classList.add('active');
    
    const r = await fetch(`/reports/api/language/${lang}`);
    const d = await r.json();
    if(d.success) {
        document.getElementById('curr-lang').textContent = lang.toUpperCase();
        const container = document.getElementById('translated-strings');
        container.innerHTML = '<div class="row g-2">'+Object.entries(d.strings).map(([k,v])=>
            `<div class="col-6"><small class="text-muted">${k}:</small><br><strong>${v}</strong></div>`
        ).join('')+'</div>';
    }
}
</script>
</body></html>'''

def init_app(app):
    app.register_blueprint(bp, url_prefix='/reports')
